package com.ipn.views;
public class jpBotonProducto extends javax.swing.JPanel {

    public jpBotonProducto(int index)  {
        initComponents();
        this.setSize(230, 30);
        this.setVisible(true);
        //se agrega un comando al boton
        this.btnProducto.setActionCommand(""+index);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProducto = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());

        btnProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnProducto.setMaximumSize(new java.awt.Dimension(15, 15));
        btnProducto.setMinimumSize(new java.awt.Dimension(15, 15));
        btnProducto.setPreferredSize(new java.awt.Dimension(100, 100));
        btnProducto.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Mayte\\Pictures\\vestido1.jpg")); // NOI18N
        add(btnProducto, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProducto;
    // End of variables declaration//GEN-END:variables



}
